
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>VCA Contact List ASP</title>    
    <link rel="stylesheet" type="text/css" href="css/site.css">
    <link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
    <script src="resources/jquery.min.js" type="text/javascript"></script>
    <script src="resources/bootstrap.min.js" type="text/javascript"></script>
<body>

    <div class="container">
        <div class="row">
            <div class=col-sm-2></div>
            <div class=col-sm-2></div>
            <div class=col-sm-2></div>
            <div class=col-sm-2></div>
            <div class=col-sm-2></div>
            <div class=col-sm-2>Sign In</div>
        </div>
    </div>


    <div class="container body-content">